### ISSUE TITLE
zwave 2.0, 2.1: Philio PAT02-1C not detected

### ISSUE THREAD

**Issue by rom169** [openhab/org.openhab.binding.zwave#361]
* OH2 Version: 2.0.0 (debian wheezy repo stable)
* Binding Version: 2.0.0 and 2.1.0.201702101116

Philio PAT02-1C is showed as active in PaperUI and Habmin but not identfied.
Device is working fine with OH1 and OH2 zwave 1.9.

It is in the database:
http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/178

Here is the node info of OH2 zwave 1.9:
```xml
<node>
  <deviceClass>
    <basicDeviceClass>ROUTING_SLAVE</basicDeviceClass>
    <genericDeviceClass>GARAGE_DOOR</genericDeviceClass>
    <specificDeviceClass>SIMPLE_GARAGE_DOOR</specificDeviceClass>
  </deviceClass>
  <homeId>0xc91ccd30</homeId>
  <nodeId>20</nodeId>
  <version>4</version>
  <name>Drainage Garten</name>
  <location>Garten</location>
  <manufacturer>0x13c</manufacturer>
  <deviceId>0x21</deviceId>
  <deviceType>0x2</deviceType>
  <listening>false</listening>
  <frequentlyListening>false</frequentlyListening>
  <routing>true</routing>
  <healState>DONE @ 2017-01-14T05:55:18+0000</healState>
  <security>false</security>
  <beaming>true</beaming>
  <maxBaudRate>40000</maxBaudRate>
  <nodeInformationFrame/>
  <supportedCommandClasses>
    <entry>
      <commandClass>BASIC</commandClass>
      <basicCommandClass>
        <version>1</version>
        <instances>1</instances>
        <isGetSupported>true</isGetSupported>
      </basicCommandClass>
    </entry>
    <entry>
      <commandClass>VERSION</commandClass>
      <versionCommandClass>
        <version>1</version>
        <instances>1</instances>
        <libraryType>LIB_SLAVE_ENHANCED</libraryType>
        <protocolVersion>4.5</protocolVersion>
        <applicationVersion>1.8</applicationVersion>
      </versionCommandClass>
    </entry>
    <entry>
      <commandClass>CONFIGURATION</commandClass>
      <configurationCommandClass>
        <version>1</version>
        <instances>1</instances>
        <configParameters>
          <entry>
            <int>1</int>
            <configurationParameter>
              <index>1</index>
              <size>1</size>
              <value>0</value>
              <readOnly>false</readOnly>
              <writeOnly>false</writeOnly>
            </configurationParameter>
          </entry>
          <entry>
            <int>2</int>
            <configurationParameter>
              <index>2</index>
              <size>1</size>
              <value>-1</value>
              <readOnly>false</readOnly>
              <writeOnly>false</writeOnly>
            </configurationParameter>
          </entry>
          <entry>
            <int>20</int>
            <configurationParameter>
              <index>20</index>
              <size>1</size>
              <value>30</value>
              <readOnly>false</readOnly>
              <writeOnly>false</writeOnly>
            </configurationParameter>
          </entry>
          <entry>
            <int>5</int>
            <configurationParameter>
              <index>5</index>
              <size>1</size>
              <value>32</value>
              <readOnly>false</readOnly>
              <writeOnly>false</writeOnly>
            </configurationParameter>
          </entry>
          <entry>
            <int>7</int>
            <configurationParameter>
              <index>7</index>
              <size>1</size>
              <value>16</value>
              <readOnly>false</readOnly>
              <writeOnly>false</writeOnly>
            </configurationParameter>
          </entry>
          <entry>
            <int>10</int>
            <configurationParameter>
              <index>10</index>
              <size>1</size>
              <value>12</value>
              <readOnly>false</readOnly>
              <writeOnly>false</writeOnly>
            </configurationParameter>
          </entry>
          <entry>
            <int>15</int>
            <configurationParameter>
              <index>15</index>
              <size>1</size>
              <value>12</value>
              <readOnly>false</readOnly>
              <writeOnly>false</writeOnly>
            </configurationParameter>
          </entry>
        </configParameters>
      </configurationCommandClass>
    </entry>
    <entry>
      <commandClass>MULTI_CMD</commandClass>
      <multiCommandCommandClass>
        <version>1</version>
        <instances>1</instances>
      </multiCommandCommandClass>
    </entry>
    <entry>
      <commandClass>BATTERY</commandClass>
      <batteryCommandClass>
        <version>1</version>
        <instances>1</instances>
        <batteryLevel>100</batteryLevel>
        <batteryLow>false</batteryLow>
        <isGetSupported>true</isGetSupported>
      </batteryCommandClass>
    </entry>
    <entry>
      <commandClass>SENSOR_BINARY</commandClass>
      <binarySensorCommandClass>
        <version>2</version>
        <instances>1</instances>
        <isGetSupported>true</isGetSupported>
      </binarySensorCommandClass>
    </entry>
    <entry>
      <commandClass>ASSOCIATION</commandClass>
      <associationCommandClass>
        <version>1</version>
        <instances>1</instances>
        <configAssociations>
          <entry>
            <int>1</int>
            <associationGroup>
              <Index>1</Index>
              <Nodes>
                <int>1</int>
              </Nodes>
            </associationGroup>
          </entry>
          <entry>
            <int>2</int>
            <associationGroup>
              <Index>2</Index>
              <Nodes/>
            </associationGroup>
          </entry>
        </configAssociations>
        <maxGroups>2</maxGroups>
      </associationCommandClass>
    </entry>
    <entry>
      <commandClass>WAKE_UP</commandClass>
      <WakeUpCommandClass>
        <version>2</version>
        <instances>1</instances>
        <targetNodeId>1</targetNodeId>
        <interval>86400</interval>
        <minInterval>1800</minInterval>
        <maxInterval>432000</maxInterval>
        <defaultInterval>86400</defaultInterval>
        <intervalStep>1800</intervalStep>
        <lastWakeup>2017-02-03 07:08:18.102 UTC</lastWakeup>
        <isGetSupported>false</isGetSupported>
      </WakeUpCommandClass>
    </entry>
    <entry>
      <commandClass>NO_OPERATION</commandClass>
      <noOperationCommandClass>
        <version>1</version>
        <instances>1</instances>
      </noOperationCommandClass>
    </entry>
    <entry>
      <commandClass>MANUFACTURER_SPECIFIC</commandClass>
      <manufacturerSpecificCommandClass>
        <version>1</version>
        <instances>1</instances>
      </manufacturerSpecificCommandClass>
    </entry>
    <entry>
      <commandClass>ALARM</commandClass>
      <alarmCommandClass>
        <version>1</version>
        <instances>1</instances>
        <alarms>
          <entry>
            <alarmType>GENERAL</alarmType>
            <alarmState>
              <alarmType>GENERAL</alarmType>
              <initialised>true</initialised>
              <outer-class reference="../../../.."/>
            </alarmState>
          </entry>
        </alarms>
        <isGetSupported>true</isGetSupported>
      </alarmCommandClass>
    </entry>
  </supportedCommandClasses>
  <nodeNeighbors>
    <int>2</int>
    <int>6</int>
    <int>9</int>
    <int>11</int>
    <int>12</int>
  </nodeNeighbors>
  <lastSent>2017-02-03 07:08:19.251 UTC</lastSent>
  <lastReceived>2017-02-03 07:08:19.871 UTC</lastReceived>
</node>
```
Regards rom169

**Comment by cdjackson** [comment]
Please provide information requested.

**Comment by rom169** [comment]
Added in the first post.

**Comment by cdjackson** [comment]
Thanks.

The reason it doesn't work is because of the version. Whoever added the data to the database set a version constraint which I suspect is not needed.

Can you double check that the parameters in the database look the same as what's in your manual and if so I'll remove this constraint and it should work.

**Comment by rom169** [comment]
OK, will do it the next couple of days. There are some comments in the database that parameter descriptions are too long. Do you want me to send you a suggestion for schorter descriptions, so you can copy the actual descriptions to the overview field?

**Comment by cdjackson** [comment]
Thanks.

It would be great if you wanted to update the database to clean these things up. If you register for an account I’ll give you access to edit directly if you like - it’s easier for us both I think :)

**Comment by rom169** [comment]
Yes, sounds good. Is this via the normal Github account or an additional account?
I will be on a business trip this week and try to find some time next weekend.


Am Sonntag, 12. Februar 2017 15:43 CET, Chris Jackson <notifications@github.com> schrieb:
 Thanks.

It would be great if you wanted to update the database to clean these things up. If you register for an account I’ll give you access to edit directly if you like - it’s easier for us both I think :)

**Comment by cdjackson** [comment]
It's a separate account at www.cd-Jackson.com. Just let me know once you register and I'll update your access rights.

**Comment by rom169** [comment]
Account for user rom169 created and activated.


Am 13.02.2017 um 15:51 schrieb Chris Jackson:
> It's a separate account at www.cd-Jackson.com. Just let me know once 
> you register and I'll update your access rights.
>
> Sent from my iPhone
>

**Comment by cdjackson** [comment]
And updated with write access - thanks.

**Comment by rom169** [comment]
Hi Chris,

I had a look on the database today and I think it's pretty straight 
forward, just a view questions occurred:

Endpoint-Command Classes:
If I do not have NIF information of a device, which ones to tick in the 
NIF Column? All beside default?
If a switch device supports BASIC and SWITCH_BINARY command class, which 
one to tick in the basic column?

Will my changes automatically be in the next build, or do you release my 
changes. I have about 10 different devices and I'm thinking about to 
check all of them for data base error messages.

Should I upload also the devices manuals? Copyrights?

If I have a sensor like the attached one, which has three different 
sensor variants, would it be better to have one database entry with 3 
types/ids or three database entries?

Regards
Andreas


Am 12.02.2017 um 15:43 schrieb Chris Jackson:

**Comment by cdjackson** [comment]
> On 17 Feb 2017, at 21:27, rom169 <notifications@github.com> wrote:
> 
> Hi Chris,
> 
> I had a look on the database today and I think it's pretty straight 
> forward, just a view questions occurred:
> 
> Endpoint-Command Classes:
> If I do not have NIF information of a device, which ones to tick in the 
> NIF Column? All beside default?

To be honest, this isn’t used anywhere - it’s really for information (as a developer I like to know sometimes for debugging, but the system doesn’t use this). Normally this is filled in from the XML file, but if you don’t have the info, don’t worry too much about ticking these...

> If a switch device supports BASIC and SWITCH_BINARY command class, which 
> one to tick in the basic column?

SWITCH_BINARY gets the basic tick - it means when we receive a BASIC, this is treated a SWITCH_BINARY.

> 
> Will my changes automatically be in the next build, or do you release my 
> changes. I have about 10 different devices and I'm thinking about to 
> check all of them for data base error messages.

I have to load them “manually” - it’s really semi auto - the files are generated automatically, but I need to manually do the PR. If you want to export yourself and create a PR you can (it can be quicker for me to process ;) ).


> Should I upload also the devices manuals? Copyrights?

I normally do - I’ve not worried too much about copywrite - my assumption is that since manufacturers are trying to sell stuff, and we’re just distributing data already available in the public domain, it shouldn’t be an issue. It’s certainly really good to have the manuals.


> If I have a sensor like the attached one, which has three different 
> sensor variants, would it be better to have one database entry with 3 
> types/ids or three database entries?

Ummm… If the device is sold as 3 variants (A/B/C?) and each variant has its own set of device type/id, then it’s probably best as 3 different devices. I’m not 100% sure though. From a quick look, if it’s really something like flood sensor, thermometer and motion sensor, then probably 3 devices.

**Comment by rom169** [comment]
So for today I updated the following devices in the DB and requested 
approval:
Philio PAT02 all three A/B/C
Philio PAN11
Fibaro FGD211 (Firmware Versions: All after 2.1)
Everspring an179 (here I uploaded just a better manual)

If I understand you correctly, you want me to export the changed devices 
as OH2 xml and post this in a PR in github?
Can this happen before the change in the database is approved?

Just want to make sure I understand the process before updating the 
other 7 devices I own.

Am 17.02.2017 um 23:06 schrieb Chris Jackson:
>

**Comment by cdjackson** [comment]
Thanks - I noticed you have been busy.

Don’t worry about the export - I’ll do this shortly (i.e. now) - it will be easier for you :) To answer your question though - yes - the export will reflect the current state of the database even if not approved.

**Comment by cdjackson** [comment]
I’ve merged the changes and kicked off a build - update should be done in 30 minutes. If you’re using apt-get or another package, then you’ll need to wait till tomorrow, but otherwise you can install once the build is done.

Thanks for your work.

**Comment by rom169** [comment]
I'm on OH2 stable and install the newest zwave binding via bundle:update 
in karaf.

I have a view strange behaviours, e.g. some switches do not update the 
item, when triggered at the device. But I can trigger the device from 
the item. Are there dependencies between OH2 core stable and OH2 binding 
snapshot?


Am 18.02.2017 um 17:07 schrieb Chris Jackson:

**Comment by cdjackson** [comment]
I wasn’t aware this new feature to load snapshots was running yet, so nice.

However, yes, it’s possible that there might have been some runtime changes - I’m not 100% sure though.

The other thing to note is that due to some runtime changes I had to change the switch_all configuration, so this might mean you need to update some config - see here -:

https://community.openhab.org/t/solved-2-10-2017-zwave-binding-broke-all-switch-things/22649/24 <https://community.openhab.org/t/solved-2-10-2017-zwave-binding-broke-all-switch-things/22649/24>

**Comment by rom169** [comment]
I changed to the snapshot repo and installed latest snapshot to avoid 
any unwanted effects by using core stable and zwave snapshot.

Philio PAT02-1C is detected now  (after I deleted the firmware reference 
in the db).

The strange effect with switches still exist. I looks like that all of 
my Philio devices (PAN06, PAN11, PST02C, PAT02C) do not update the 
items, when the switch is triggered at the device (e.g. door opens or 
wall switch triggered to turn on light). On the other hand, battery 
status or other measurements are reported correctly and I can trigger 
the switch via the item (PAN06, PAN11).

I get a similar effect with Fibaro FGS222. Here the switch_binary2 
updates the item correctly, switch_binary1 does not.

Should I open new issues for this topics?

During the next weeks I will go on to rework the database error messages 
of all the devices I use. Just one question here, as I have seen in the 
Habmin zwave network viewer, that battery device are associating with 
each other, which seems strange for me, as they are not always on. Is it 
correct to set battery devices in the db to "Supports Routing = yes"?


Am 18.02.2017 um 21:00 schrieb Chris Jackson:

**Comment by cdjackson** [comment]
>  I have seen in the Habmin zwave network viewer, that battery device are associating with
each other,

I'm not sure what you mean? Do you mean that battery devices are seen as neighbours of other battery devices? This is fine - it doesn't mean they are used for routing - routing is configured by the controller itself.

> Is it correct to set battery devices in the db to "Supports Routing = yes"?

No - you shouldn't change these - this information comes from the XML file, which in turn comes from the device. It's not actually used by the database since the binding uses the information from the device, but the database should be correct or it could be confusing.

Generally battery devices don't participate in routing since they are normally not listening.

**Comment by cdjackson** [comment]
As stated above, the device is now detected so closing
